### PR TITLE
update API

### PR DESCRIPTION
**Pull request by mahmoud-alragabi**

### CODE REVIEW

**Review by HallaqAmer — COMMENTED** [review]
Hi Mahmoud,

For ratings, the data will be in the following form:

reviews: [

        {
        ProductId:string,
        UserId: string,
        content:string,
        rating: number
}       
]

**Comment by mahmoud-alragabi** [comment]
> Hi Mahmoud,
> 
> For ratings, the data will be in the following form:
> 
> reviews: [
> 
> ```
>     {
>     ProductId:string,
>     UserId: string,
>     content:string,
>     rating: number
> ```
> 
> } ]

thank you I'll add it now

**Review by HallaqAmer — APPROVED** [review]
Approved

**Review by ferassmohana — APPROVED** [review]

**Review by ileenshaar — APPROVED** [review]

**Review by Mahmoud040 — COMMENTED** [review]
Noted!

**Pull request merged**
